version: "3.9"

services:
  aura-agent:
    build: .
    container_name: aura_agent
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/app
    restart: always

  redis:
    image: redis:7-alpine
    container_name: aura_redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15-alpine
    container_name: aura_postgres
    environment:
      POSTGRES_DB: aura_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
