[tool.ruff]
target-version = "py313"
line-length = 88
extend-exclude = [
    "*/migrations/*.py",
    ".venv",
    "venv",
    "tests/fixtures/*"
]
src = ["agent_service"]

[tool.ruff.lint]
select = [
  "F", "E", "W", "C90", "I", "N", "UP", "ASYNC", "S", "BLE", "FBT", "B", "A", "COM",
  "C4", "DTZ", "T10", "EM", "EXE", "FA", "ISC", "ICN", "G", "INP", "PIE", "T20", "PYI",
  "PT", "Q", "RSE", "RET", "SLF", "SLOT", "SIM", "TID", "INT", "PTH", "ERA", "PD",
  "PGH", "PL", "TRY", "FLY", "PERF", "RUF"
]
ignore = [
  "S101",     # Use of assert
  "RUF012",   # Mutable class vars
  "SIM102",   # Nested ifs
  "UP038",    # isinstance(tuple) perf issues
]

[tool.ruff.lint.isort]
force-single-line = true

[tool.ruff.format]
quote-style = "preserve"
docstring-code-format = true

[tool.mypy]
python_version = "3.13"
check_untyped_defs = true
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
exclude = ["tests/helpers", "scripts/tmp"]  # Optional

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--import-mode=importlib"
testpaths = ["tests"]
python_files = [
    "tests.py",
    "test_*.py"
]

[tool.coverage.run]
source = ["agent_service"]
omit = ["*/tests/*", "*/migrations/*"]
